root -l -q -b "GetSignalEfficiencyPerMassBinAll.C(\""Schannel\"")"
root -l -q -b "GetSignalEfficiencyPerMassBinAll.C(\""Tchannel\"")"
root -l -q -b "GetSignalEfficiencyPerMassBinAll.C(\""Combinedchannel\"")"
root -l -q -b "GetSignalEfficiencyPerMassBin.C(\""Schannel\"")"
root -l -q -b "GetSignalEfficiencyPerMassBin.C(\""Tchannel\"")"
root -l -q -b "GetSignalEfficiencyPerMassBin.C(\""Combinedchannel\"")"
